name: pokechallenge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_sticky_header: ^0.6.3
  get_it: ^7.1.2
  graphql: ^5.1.1
  path_provider: ^2.0.1
  sembast: ^3.1.0+2

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.0.0


flutter:
  uses-material-design: true